Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,6 +37,17 @@ jobs:
           key: ${{ secrets.SSH_ROOT_KEY }}
           port: ${{ secrets.SSH_ROOT_PORT }}
           script: |
+            if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
+              echo "docker-compose not found, installing..."
+              # Установка плагина docker-compose (Ubuntu / Debian)
+              apt-get update
+              apt-get install -y docker-compose-plugin
+              # Либо fallback: классический docker-compose
+              if ! command -v docker compose &> /dev/null; then
+                curl -SL "https://github.com/docker/compose/releases/download/v2.39.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                chmod +x /usr/local/bin/docker-compose
+              fi
+            fi
             # если директория ещё не существует — клонировать
             if [ ! -d /root/app ]; then
               git clone https://github.com/haranton/online_shop_Golang.git /root/app
